CREATE TABLE "FID_DATOS_EST_CTAS" (	
    "DAT_CONTRATO" INT NOT NULL, 
    "DAT_NIVEL" INT NOT NULL, 
    "DAT_ID" INT NOT NULL, 
    "DAT_PARENT_ID" INT NOT NULL, 
    "DAT_CLAVE" VARCHAR(30) NOT NULL, 
    "DAT_DATO" VARCHAR(250) NOT NULL, 
    "DAT_DESCRIPCION" VARCHAR(300), 
    "DAT_FEC_ALTA" DATE NOT NULL, 
    "DAT_FEC_ULT_MOD" DATE NOT NULL, 
    "DAT_ESTATUS" VARCHAR(30) NOT NULL, 
    "DAT_FEC_BAJA" DATE, 
    CONSTRAINT "FID_DATOS_EST_CTAS_PK" PRIMARY KEY ("DAT_CONTRATO", "DAT_CLAVE")
);