
CREATE TABLE SALDOSSIRJUM (
    MOV_CONTRATO INT NOT NULL, 
	MOV_CLAVE_INV VARCHAR(30) NOT NULL, 
	MOV_SECUENCIAL INT NOT NULL, 
	MOV_FEC_OPER DATE NOT NULL, 
	MOV_TIPO_OPER VARCHAR(1) NOT NULL, 
	MOV_IMPORTE DECIMAL(35,8) NOT NULL, 
	MOV_FEC_ALTA DATE NOT NULL, 
	MOV_FEC_ULT_MOD DATE NOT NULL, 
	MOV_ESTATUS VARCHAR(30) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;