services:
  app:
    build: .
    ports:
      - 10101:10101
    depends_on:
      - db
    volumes:
      - ./src/main/resources:/app/src/main/resources
      - ./trusts:/app/trusts
  db:
    image: mysql:latest
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trust
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: 