version: '3.8'

services:
  app:
    build: .
    ports:
      -"8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:53306/trusts
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  db:
    image: mysql:8.0
    ports:
      - "53306:53306"
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: trust
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
    volumes:
      - db-data: /var/lib/mysql
  volumes:
    db-data: 