services:
  db:
    image: mysql:latest
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trust
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    ports:
      - 10101:10101
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/main/resources:/app/src/main/resources
      - ./trusts:/app/trusts

volumes:
  db-data: 