spring.application.name=BCB Trusts Management
spring.config.import=optional:file:.env[.properties]
spring.main.allow-bean-definition-overriding=true

server.port=10101
#server.error.whitelabel.enabled=false
#server.error.path=/error
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

# Hibernate is disabled because Liquibase will manage schema
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=${DATABASE_JDBC_URL}
spring.liquibase.user=${DATABASE_USERNAME}
spring.liquibase.password=${DATABASE_PASSWORD}
spring.liquibase.driver-class-name=${DATABASE_DRIVER_CLASSNAME}

trusts.datasource.jdbc-url=${DATABASE_JDBC_URL}
trusts.datasource.username=${DATABASE_USERNAME}
trusts.datasource.password=${DATABASE_PASSWORD}
trusts.datasource.driverClassName=${DATABASE_DRIVER_CLASSNAME}
trusts.datasource.hikari.connectionTimeout=30000
trusts.datasource.hikari.idleTimeout=30000
trusts.datasource.hikari.maxLifetime=1800000
spring.jpa.database-platform=${DATABASE_PLATFORM}

# BMTKFWEB PROD
#bmtkfweb.datasource.jdbc-url=jdbc:oracle:thin:@10.10.50.16:1527/BMTKFWEB
# BMTKFWEB QA
#bmtkfweb.datasource.jdbc-url=jdbc:oracle:thin:@10.20.50.200:1528/BMTKFWEB
bmtkfweb.datasource.jdbc-url=${LEGACY_DB_JDBC_URL}
bmtkfweb.datasource.username=${LEGACY_DB_USERNAME}
bmtkfweb.datasource.password=${LEGACY_DB_PASSWORD}
bmtkfweb.datasource.driver-class-name=${LEGACY_DB_DRIVER_CLASSNAME}
bmtkfweb.datasource.jpa.hibernate.dialect=${LEGACY_HIBERNATE_DIALECT}
bmtkfweb.datasource.hikari.minimum-idle=5
bmtkfweb.datasource.hikari.maximum-pool-size=20
bmtkfweb.datasource.hikari.connection-timeout=30000
bmtkfweb.datasource.hikari.idle-timeout=600000
bmtkfweb.datasource.hikari.max-lifetime=1800000
bmtkfweb.datasource.hikari.pool-name=OracleDBHikariCP
bmtkfweb.datasource.hikari.validation-timeout=5000
bmtkfweb.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

