
ELSIF TIPO = 2 OR TIPO=7 OR TIPO=9 THEN --ESTADO DE CUENTA POR INVERSIONISTA ALTA

      SELECT NVL(DAT_FEC_BAJA,''), NVL(DAT_FEC_ALTA,'') INTO FECHABAJA, FECHAALTA FROM fid_datos_est_ctas WHERE DAT_CLAVE=N2 and DAT_CONTRATO=FIDEICOMISO;
      --FECHAFINAL:=FECHAALTA;
      /*IF LENGTH(FECHABAJA)>0 AND FECHABAJA<>NULL THEN
        IF FECHABAJA<FECHAFINAL THEN
          FECHAFINAL:=FECHABAJA;
        END IF;
      END IF;*/
      IF NVL(OFICIO,'NULO')<>'MASIVO' THEN
       DELETE FROM REPCTAIND WHERE RCI_NUM_N2=N2;
        DELETE FROM FID_RES_CTAS_IND WHERE SAL_CLAVE_INV=N2;
      END IF;
      PDT_INI := REPLACE('01'||SUBSTR(FECHAFINAL, 3, LENGTH(FECHAFINAL)),' ','');

      IF TIPO=2 THEN
        VRCI_PERIODO := PDT_INI || ' al ' || FECHAFINAL;      
      ELSE
        VRCI_PERIODO := FECHAINICIAL || ' al ' || FECHAFINAL;      
      END IF;
      /*DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'ARCHIVO',FECHABAJA);
      COMMIT;
      IF NVL(FECHABAJA,'VACIO')<>'VACIO' THEN
        FECHAFINAL:=TO_CHAR(FECHABAJA,'DD/MM/YYYY');
      END IF; 
      */
      IF NVL(FECHAINICIAL,'VACIO')<>'VACIO'  AND TIPO=2 THEN
        SELECT TRUNC(MONTHS_BETWEEN( TO_DATE(FECHAINICIAL,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
      ELSE
          --MODIFICACION DEL 05/06/2023
          IF NVL(TO_CHAR(FECHABAJA,'DD/MM/YYYY'),'01/01/1900')<>'01/01/1900' THEN
            SELECT TRUNC(MONTHS_BETWEEN(FECHABAJA, FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            --INSERT INTO ARCHIVOS_PLANOS VALUES (2, SYSDATE,'ARCHIVO',FECHABAJA);
          ELSE
            --SELECT TRUNC(MONTHS_BETWEEN(TO_DATE(FECHA_CORTE,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            SELECT TRUNC(MONTHS_BETWEEN( TO_DATE(FECHAFINAL,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            --INSERT INTO ARCHIVOS_PLANOS VALUES (2, SYSDATE,'ARCHIVO',FECHA_CORTE);
          END IF;
      END IF;

      /*IF NANIOS<29 THEN      
        SELECT DER_PCJ INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
      ELSE
        NPORCENTAJE:=0;
      END IF;*/


      IF NANIOS<29 THEN      
        SELECT COUNT(1) INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);

        IF NPORCENTAJE>0 THEN
          SELECT DER_PCJ INTO NPORCENTAJE
          FROM FID_DER_ADQ
          WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
        ELSE
          NPORCENTAJE:=1;
        END IF;  
      ELSE
        NPORCENTAJE:=1;
      END IF;
     /* IF NPORCENTAJE=0 THEN
        NPORCENTAJE:=100;
      END IF;*/

      --SE EJECUTA EL PROCEDIMIENTO QUE DETERMINA LOS SALDOS PARA EL INVERSIONISTA EN CUESTION
      --DELETE FID_RES_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO and SAL_CLAVE_INV=N2;
      /*DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'ARCHIVO',NPORCENTAJE);
      COMMIT;*/

      INSERT INTO FID_RES_CTAS_IND
      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'SA' ID,
        0 TRABAJADOR,
        0 AYUNTAMIENTO,
        TO_NUMBER(
        TO_CHAR((NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3,5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0)-
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3,5,6) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0)),'999,999,999,999,990.00'),'999,999,999,999,990.00') TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER < TO_DATE(FECHAINICIAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'D' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'R' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'I' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'S' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,--TO_CHAR(NPORCENTAJE,'000') || '%',
        'DA' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * (NPORCENTAJE/100)
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,            
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99') || '%',NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE  MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        --TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO;

      IF TIPO=2 THEN
        UPDATE FID_RES_CTAS_IND SET
        SAL_TOTAL=0
        WHERE
        SAL_CONTRATO=FIDEICOMISO AND
        SAL_CLAVE_INV=N2 AND
        ID='SA';
      END IF;

      IF TIPO=2 THEN  
        VSQL:= '
            SELECT 
              MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN MOV_IMPORTE
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN MOV_IMPORTE
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND';
      ELSIF TIPO=7 THEN
        VSQL:= '
            SELECT '''||FECHAFINAL|| 
                ''' MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN SUM(MOV_IMPORTE)
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN SUM(MOV_IMPORTE)
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND';
      ELSE--PARA EL CASO DE ESTADO DE CUENTA CON SUBRANGO        
        IF SUBRANGO='BIMESTRE' THEN
            VSQL:= 'SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
                CASE
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN ''BIMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN ''BIMESTRE 2''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN ''BIMESTRE 3''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN ''BIMESTRE 4'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN ''BIMESTRE 5''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN ''BIMESTRE 6''
                END AS PERIODO,
                SUM
                (
                CASE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN MOV_IMPORTE ELSE 0
                END) AS DEPOSITOS,
                SUM
                (
                CASE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN MOV_IMPORTE ELSE 0
                END) AS RETIROS,            
                  CASE 
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                    ELSE MOV_OFICIO
                  END DESCRIPCION';
        ELSIF SUBRANGO='TRIMESTRE' THEN
            VSQL:= 'SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN ''TRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN ''TRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN ''TRIMESTRE 3''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN ''TRIMESTRE 4''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='CUATRIMESTRE' THEN    
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN ''CUATRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN ''CUATRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN ''CUATRIMESTRE 3''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='SEMESTRE' THEN
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN ''SEMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN ''SEMESTRE 2''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='ANUAL' THEN      
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN ''ANUAL'' 
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        END IF;
        VSQL:=VSQL||' FROM FID_MOV_CTAS_IND
        WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9)';
      END IF;
      IF TIPO=2 THEN
        VSQL:=VSQL||' MOV_FEC_OPER <= ''' || FECHAFINAL || '''';
        VSQL:= VSQL||' ORDER BY 1,2';            
      ELSIF TIPO=7 THEN
        VSQL:=VSQL||' MOV_FEC_OPER BETWEEN ''' || FECHAINICIAL || ''' AND '''||FECHAFINAL||'''';
        VSQL:= VSQL||' GROUP BY MOV_CLAV
        E_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 2';
      ELSE
        VSQL:=VSQL||' AND MOV_FEC_OPER BETWEEN ''' || FECHAINICIAL || ''' AND '''||FECHAFINAL||'''';
        IF SUBRANGO='BIMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN ''BIMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN ''BIMESTRE 2''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN ''BIMESTRE 3''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN ''BIMESTRE 4'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN ''BIMESTRE 5''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN ''BIMESTRE 6''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                ORDER BY 1,2,5';
        ELSIF SUBRANGO='TRIMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN ''TRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN ''TRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN ''TRIMESTRE 3''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN ''TRIMESTRE 4''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                ORDER BY 1,2,5';
        ELSIF SUBRANGO='CUATRIMESTRE' THEN        
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN ''CUATRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN ''CUATRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN ''CUATRIMESTRE 3''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 1,2,5';
        ELSIF SUBRANGO='SEMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                    CASE 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN ''SEMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN ''SEMESTRE 2''
                    END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                           ORDER BY 1,2,5';
        ELSIF SUBRANGO='ANUAL' THEN      
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN ''ANUAL'' 
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 1,2,5';        
        END IF;
      END IF;

        OPEN RS_REPCTASIND2 FOR VSQL;
        LOOP
          NRCI_DEPOSITOS:=0;
          NRCI_RETIROS:=0;
          IF TIPO=9 THEN
            FETCH RS_REPCTASIND2 INTO VRCI_FECHA_ANIO,VRCI_FECHA_PERIODO,NRCI_DEPOSITOS,NRCI_RETIROS,VDATOS;
          ELSE
            FETCH RS_REPCTASIND2 INTO VRCI_FECHA,VDATOS,NRCI_DEPOSITOS,NRCI_RETIROS;
          END IF;

          EXIT WHEN RS_REPCTASIND2%NOTFOUND;

          NPARTICIPACION:= NPARTICIPACION + NRCI_DEPOSITOS - NRCI_RETIROS;

          IF TIPO=9 THEN
            VRCI_FECHA:=VRCI_FECHA_PERIODO||' '||VRCI_FECHA_ANIO;  
          END IF;  

          IF NRCI_DEPOSITOS<>0 OR NRCI_RETIROS<>0 THEN
            IF TIPO=2 THEN                            
                INSERT INTO REPCTAIND VALUES (
                  NSECUENCIAL,
                  FIDEICOMISO,
                  VRCI_NOM_FIDEICOMISO,
                  VRCI_PERIODO,--PERIODO
                  VRCI_FECHA,
                  NOMN1,--NOMBRE DE NIVEL 1
                  NOMN2,--NOMBRE DE NIVEL 2
                  NOMN3,--NOMBRE DE NIVEL 3
                  VDATOS,
                  N1,
                  N2,
                  N3,
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                  0,--NUMERO DE INVERSIONISTAS
                  NPARTICIPACION,--SALDO ANTERIOR
                  NRCI_TASA,
                  NRCI_DEPOSITOS,
                  NRCI_RETIROS,
                  NRCI_INTERESES,--INTERESES
                  NRCI_ISR,--ISR
                  NPARTICIPACION,--SALDO PARCIAL
                  TIPO,--TIPO ESTADO DE CUENTA
                  NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                );
            ELSIF TIPO= 7 THEN
                --PARA EL CASO DE INTERESES SE DESCARTAN LOS RETIROS
                IF INSTR(VDATOS,'INTERES')>0 THEN
                    NRCI_DEPOSITOS:= NRCI_DEPOSITOS - NRCI_RETIROS;
                    NRCI_RETIROS:=0;
                END IF;

                SELECT COUNT(1) INTO NDATOS 
                FROM REPCTAIND
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_NOM_INVERS=VDATOS AND
                RCI_NUM_N2=N2;

                IF NDATOS=0 THEN
                    INSERT INTO REPCTAIND VALUES (
                      NSECUENCIAL,
                      FIDEICOMISO,
                      VRCI_NOM_FIDEICOMISO,
                      VRCI_PERIODO,--PERIODO
                      VRCI_FECHA,
                      NOMN1,--NOMBRE DE NIVEL 1
                      NOMN2,--NOMBRE DE NIVEL 2
                      NOMN3,--NOMBRE DE NIVEL 3
                      VDATOS,
                      N1,
                      N2,
                      N3,
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                      0,--NUMERO DE INVERSIONISTAS
                      NPARTICIPACION,--SALDO ANTERIOR
                      NRCI_TASA,
                      NRCI_DEPOSITOS,
                      NRCI_RETIROS,
                      NRCI_INTERESES,--INTERESES
                      NRCI_ISR,--ISR
                      NPARTICIPACION,--SALDO PARCIAL
                      TIPO,--TIPO ESTADO DE CUENTA
                      NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                    );
                ELSE
                    UPDATE REPCTAIND SET
                    RCI_DEPOSITOS=RCI_DEPOSITOS+NRCI_DEPOSITOS,
                    RCI_RETIROS=RCI_RETIROS+NRCI_RETIROS
                    WHERE
                    RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                    RCI_NOM_INVERS=VDATOS AND
                    RCI_NUM_N2=N2;                   
                END IF;
            ELSE  
                --PARA EL CASO DE INTERESES SE DESCARTAN LOS RETIROS
                IF INSTR(VDATOS,'INTERES')>0 THEN
                    NRCI_DEPOSITOS:= NRCI_DEPOSITOS - NRCI_RETIROS;
                    NRCI_RETIROS:=0;
                END IF;

                SELECT COUNT(1) INTO NDATOS 
                FROM REPCTAIND
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_NOM_INVERS=VDATOS AND
                RCI_NUM_N2=N2 AND
                RCI_FECHA=VRCI_FECHA;

                IF NDATOS=0 THEN
                    INSERT INTO REPCTAIND VALUES (
                      NSECUENCIAL,
                      FIDEICOMISO,
                      VRCI_NOM_FIDEICOMISO,
                      VRCI_PERIODO,--PERIODO
                      VRCI_FECHA,
                      NOMN1,--NOMBRE DE NIVEL 1
                      NOMN2,--NOMBRE DE NIVEL 2
                      NOMN3,--NOMBRE DE NIVEL 3
                      VDATOS,
                      N1,
                      N2,
                      N3,
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                      0,--NUMERO DE INVERSIONISTAS
                      NPARTICIPACION,--SALDO ANTERIOR
                      NRCI_TASA,
                      NRCI_DEPOSITOS,
                      NRCI_RETIROS,
                      NRCI_INTERESES,--INTERESES
                      NRCI_ISR,--ISR
                      NPARTICIPACION,--SALDO PARCIAL
                      TIPO,--TIPO ESTADO DE CUENTA
                      NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                    );
                ELSE
                    UPDATE REPCTAIND SET
                    RCI_DEPOSITOS=RCI_DEPOSITOS+NRCI_DEPOSITOS,
                    RCI_RETIROS=RCI_RETIROS+NRCI_RETIROS
                    WHERE
                    RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                    RCI_NOM_INVERS=VDATOS AND
                    RCI_NUM_N2=N2 AND
                    RCI_FECHA=VRCI_FECHA;                   
                END IF;           
            END IF;
          END IF;        

        NSECUENCIAL := NSECUENCIAL + 1;
      END LOOP;
      CLOSE RS_REPCTASIND2;

        OPEN RS_REPCTASIND2 FOR 
        SELECT RCI_SECUENCIAL,RCI_FECHA,RCI_DEPOSITOS,RCI_RETIROS 
        FROM REPCTAIND
        WHERE RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
        RCI_NUM_N2=N2
        ORDER BY RCI_SECUENCIAL ASC;
        LOOP
            FETCH RS_REPCTASIND2 INTO NSECUENCIAL,VRCI_FECHA_ANIO,NRCI_DEPOSITOS,NRCI_RETIROS;
            EXIT WHEN RS_REPCTASIND2%NOTFOUND;
            IF NRCI_DEPOSITOS<0 THEN
                NRCI_RETIROS:=NRCI_DEPOSITOS*-1;
                NRCI_DEPOSITOS:=0;

                UPDATE REPCTAIND SET
                RCI_DEPOSITOS=NRCI_DEPOSITOS,
                RCI_RETIROS=NRCI_RETIROS
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_SECUENCIAL=NSECUENCIAL AND
                RCI_FECHA=VRCI_FECHA_ANIO AND
                RCI_NUM_N2=N2;               
            END IF;
        END LOOP;
        CLOSE RS_REPCTASIND2;

     /* SELECT COUNT(1) INTO NDATOS
      FROM FID_RES_CTAS_IND WHERE ID='SA';
      IF NDATOS=0 THEN
        INSERT INTO FID_RES_CTAS_IND VALUES (PDT_INI,FIDEICOMISO,N2,'SA',0,0,0);
      END IF;*/
    