FUNCTION REPORTES(TIPO NUMBER,FIDEICOMISO NUMBER,FECHAINICIAL VARCHAR2,VFECHAFINAL IN VARCHAR2,N1 VARCHAR2,N2 VARCHAR2,N3 VARCHAR2,
NOMN1 VARCHAR2,NOMN2 VARCHAR2,NOMN3 VARCHAR2,NUMNIVEL NUMBER,OFICIO VARCHAR2,ACUERDO VARCHAR2,BENEFICIARIO VARCHAR2,SUBRANGO VARCHAR2) RETURN NUMBER
AS
  BEGIN
    DECLARE
      AUX_ORA_ERR VARCHAR(255);
      AUX_MSG_ERR VARCHAR2(512);
      AUX_STATUS  VARCHAR2(15);
      NDATOS NUMBER;
      VDATOS VARCHAR2(500);
      TYPE RF_CURSOR IS REF CURSOR;
      RS_REPCTASIND RF_CURSOR;
      RS_REPCTASIND2 RF_CURSOR;
      RS_NIVELES  RF_CURSOR;
      NSECUENCIAL NUMBER;
      NRCI_NUM_FIDEICOMISO REPCTAIND.RCI_NUM_FIDEICOMISO %TYPE;
      VRCI_NOM_FIDEICOMISO REPCTAIND.RCI_NOM_FIDEICOMISO %TYPE;
      VRCI_NOM_INVERS REPCTAIND.RCI_NOM_INVERS %TYPE;
      VRCI_PERIODO REPCTAIND.RCI_PERIODO %TYPE;
      VRCI_FECHA REPCTAIND.RCI_FECHA %TYPE;
      NRCI_NUM_N1 REPCTAIND.RCI_NUM_N1 %TYPE;
      NRCI_NUM_N2 REPCTAIND.RCI_NUM_N2 %TYPE;
      NRCI_NUM_N3 REPCTAIND.RCI_NUM_N3 %TYPE;
      VRCI_NOM_N1 REPCTAIND.RCI_NOM_N1 %TYPE;
      VRCI_NOM_N2 REPCTAIND.RCI_NOM_N2 %TYPE;
      NRCI_TASA REPCTAIND.RCI_TASA %TYPE;
      NRCI_NUM_INVER REPCTAIND.RCI_NUM_INVER %TYPE;
      NRCI_SALDO_ANT REPCTAIND.RCI_SALDO_ANT %TYPE;
      NRCI_DEPOSITOS REPCTAIND.RCI_DEPOSITOS %TYPE;
      NRCI_RETIROS REPCTAIND.RCI_RETIROS %TYPE;
      NRCI_INTERESES REPCTAIND.RCI_INTERESES %TYPE;
      NRCI_ISR REPCTAIND.RCI_ISR %TYPE;
      NRCI_PARTICIPACION REPCTAIND.RCI_PARTICIPACION %TYPE;
      NRCI_SALDO_FINAL REPCTAIND.RCI_SALDO_FINAL %TYPE;
      NTITULOS NUMBER;
      VPARTICIPACION VARCHAR2(100);
      NNIVEL NUMBER;
      NPARTICIPACION NUMBER;
      NPORCPARTICIPA NUMBER;
      VSQL VARCHAR2(5000);
      VN1 VARCHAR2(100);
      PN_NUMFISO NUMBER; PDT_INI VARCHAR2(10); PDT_FIN VARCHAR2(10); PN_NIVEL VARCHAR2(200);
      DULTFECHA DATE;
      VTITULO VARCHAR2(1000);
      VMININV VARCHAR2(50);
      VMAXINV VARCHAR2(50);
      VTEMPO VARCHAR2(255);
      CONTNIVEL NUMBER;
      NLONGINI NUMBER;
      VNOMBREAUX VARCHAR2(500);
      VNOMBREAUX2     VARCHAR2(500);
      NUMNIVELES NUMBER;
      NCONTPARTICIP NUMBER;
      NCONTPARTICIPAUX NUMBER;
      ARR_PARTICIPACION NDATO2;
      NPARTICIPACUM NUMBER;
      NDATOS3 NUMBER;
      NSECUENCIALVALOR NUMBER;
      VFECHATEMPFINAL VARCHAR2(10);
      FECHAFINAL VARCHAR2(10);
      VFECCONT VARCHAR2(10);
      NANIOS NUMBER := 0;
      NPORCENTAJE NUMBER := 0;

      NDEPOSITOSANTERIOR NUMBER :=0;
      NRETIROSANTERIOR NUMBER :=0;
      NINTERESESANTERIOR NUMBER :=0;

      VACUERDO VARCHAR2(500);
      VOFICIO VARCHAR2(500);
      VBENEFICIARIO VARCHAR2(500);
      FECHABAJA DATE;
      VCLAVEEMPLEADOCTASINDIV VARCHAR2(255);      
      FECHAALTA DATE;

      VRCI_FECHA_ANIO VARCHAR2(100);
      VRCI_FECHA_PERIODO VARCHAR2(100);
    BEGIN
    IF NVL(OFICIO,'NULO')<>'MASIVO' THEN
        DELETE FROM REPCTAIND;
        DELETE FROM FID_RES_CTAS_IND;
    END IF;
    FECHABAJA:='';
    FECHAALTA:='';

    SELECT REPLACE(TO_CHAR(FCO_DIA_APLI_CONTA, '00') || '/' || TO_CHAR(FCO_MES_APLI_CONTA, '00') || '/' || TO_CHAR(FCO_ANO_APLI_CONTA, '0000'), ' ', '') INTO VFECCONT
    FROM FECCONT;

    --SE OBTIENE EL NOMBRE DEL FIDEICOMISO EN CUESTION
    SELECT CTO_NOM_CONTRATO INTO VRCI_NOM_FIDEICOMISO
    FROM CONTRATO WHERE CTO_NUM_CONTRATO=FIDEICOMISO;
    --SE DETERMINA SI MANEJA O NO PARTICIPACION
    SELECT COUNT(1) INTO NDATOS
    FROM FID_PARTICIPACION
    WHERE PAR_CONTRATO=FIDEICOMISO AND
    PAR_NIVEL = NUMNIVEL;
    IF NDATOS > 0 THEN
      SELECT PAR_CLAVE INTO VPARTICIPACION
      FROM FID_PARTICIPACION
      WHERE PAR_CONTRATO=FIDEICOMISO AND
      PAR_NIVEL = NUMNIVEL;
    ELSE
      VPARTICIPACION:='';
    END IF;
    /*SELECT COUNT(1) INTO NDATOS
    FROM PARAM_FISOS
    WHERE
    CTO_NUM_CONTRATO=FIDEICOMISO;
    IF NDATOS>0 THEN
      SELECT PCTO_PARTICIP INTO NPORCPARTICIPA
      FROM PARAM_FISOS
      WHERE
      CTO_NUM_CONTRATO=FIDEICOMISO AND
      CTAS_INDIVIDUALES=1;
    ELSE
      RETURN 2;
    END IF;*/
    NSECUENCIAL:=0;
    --SE VALIDA LA FECHA Y EN SU CASO SE CORRIGE
    --VFECHATEMPFINAL:=F_REGRESA_FECHA(VFECHAFINAL,1,2,0);
    FECHAFINAL:=VFECHAFINAL;
    VRCI_PERIODO:=FECHAINICIAL||' AL '||FECHAFINAL;
    IF TIPO = 1 THEN--MOVIMIENTOS DE DEPOSITO Y RETIRO
      VSQL:= 'SELECT TO_NUMBER(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
      VSQL:=VSQL || '= 1) )) AS N1,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = RPAD(   ';
      VSQL:=VSQL || '(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 1)   ';
      VSQL:=VSQL || ')), LENGTH(MOV_CLAVE_INV), ''0'' )) AS NomN1,  ';
      VSQL:=VSQL || 'TO_NUMBER(SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
      VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) AS N2,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = RPAD(   ';
      VSQL:=VSQL || '(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 1)   ';
      VSQL:=VSQL || ')) || (SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL   ';
      VSQL:=VSQL || '= 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) ,   ';
      VSQL:=VSQL || 'LENGTH(MOV_CLAVE_INV), ''0'' )) AS NomN2,  ';
      VSQL:=VSQL || 'TO_NUMBER(SUBSTR(MOV_CLAVE_INV, (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
      VSQL:=VSQL || 'EST_NIVEL <= 2) )) AS N3,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = MOV_CLAVE_INV) AS   ';
      VSQL:=VSQL || 'NOMBRE,   ';
      VSQL:=VSQL || 'TO_CHAR(MOV_FEC_OPER,''DD/MM/YYYY'' ) AS MOV_FEC_OPER,  ';
      --VSQL:=VSQL || 'MOV_CLAVE_INV ,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''D'',MOV_IMPORTE,0),0) AS DEPOSITO,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''R'',MOV_IMPORTE,0),0) AS RETIRO ,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''I'',MOV_IMPORTE,0),0) AS INTERES ,  ';      
      VSQL:=VSQL || 'MOV_CONTRATO,   ';
      VSQL:=VSQL || 'LENGTH(MOV_CLAVE_INV)   ';
      VSQL:=VSQL || 'FROM   FID_MOV_CTAS_IND  ';
      VSQL:=VSQL || 'WHERE  MOV_CONTRATO = '||TO_CHAR(FIDEICOMISO);
      VSQL:=VSQL || 'AND    MOV_FEC_OPER BETWEEN TO_DATE('''||FECHAINICIAL||''',''DD/MM/YYYY'') AND TO_DATE('''||VFECHAFINAL||''',''DD/MM/YYYY'')  ';
      --VSQL:=VSQL || 'AND    MOV_TIPO_OPER <> ''I''';
      /*IF LENGTH(VPARTICIPACION) > 0 THEN
        VSQL:=VSQL || ' AND MOV_CLAVE_INV='''||VPARTICIPACION||'''';
      END IF;*/
      IF INSTR(N1,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
        VSQL:=VSQL || '= 1) ))=SUBSTR('''||N1||''', 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
        VSQL:=VSQL || '= 1) )';
      END IF;
      IF INSTR(N2,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) =SUBSTR(''';
        VSQL:=VSQL || N2||''', (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )';
      END IF;
      IF INSTR(N3,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL <= 2) ))=SUBSTR(''';
        VSQL:=VSQL || N3||''', (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL <= 2) )';
      END IF;
      OPEN RS_REPCTASIND FOR VSQL;
      LOOP
        FETCH RS_REPCTASIND INTO NRCI_NUM_N1,VRCI_NOM_N1,NRCI_NUM_N2,VRCI_NOM_N2,NRCI_NUM_N3,VRCI_NOM_INVERS,VRCI_FECHA,NRCI_DEPOSITOS,NRCI_RETIROS,
        NRCI_INTERESES,NRCI_NUM_FIDEICOMISO,NRCI_NUM_INVER;
        EXIT WHEN RS_REPCTASIND%NOTFOUND;

          INSERT INTO REPCTAIND VALUES (
            NSECUENCIAL,FIDEICOMISO,VRCI_NOM_FIDEICOMISO,
            VRCI_PERIODO,--PERIODO
            VRCI_FECHA,
            NOMN1,--NOMBRE DE NIVEL 1
            NOMN2,--NOMBRE DE NIVEL 2
            NOMN3,--NOMBRE DE NIVEL 3
            VRCI_NOM_INVERS,
            NRCI_NUM_N1,NVL(NRCI_NUM_N2,0),NVL(NRCI_NUM_N3,0),
            VRCI_NOM_N1,VRCI_NOM_N2,
            0,--NUMERO DE INVERSIONISTAS
            0,--SALDO ANTERIOR
            0,--TASA
            NRCI_DEPOSITOS,NRCI_RETIROS,
            NRCI_INTERESES,--INTERESES
            0,--ISR
            0,--PARTICIPACION
            0,--SALDO PARCIAL
            0,'N/A','N/A','N/A'--SALDO FINAL
          );
        NSECUENCIAL:=NSECUENCIAL+1;
      END LOOP;
      CLOSE RS_REPCTASIND;

    ELSIF TIPO = 6 THEN--ESTADO DE CUENTA FOFAE
      VSQL:= 'SELECT TO_NUMBER(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
      VSQL:=VSQL || '= 1) )) AS N1,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = RPAD(   ';
      VSQL:=VSQL || '(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 1)   ';
      VSQL:=VSQL || ')), LENGTH(MOV_CLAVE_INV), ''0'' )) AS NomN1,  ';
      VSQL:=VSQL || 'TO_NUMBER(SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
      VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) AS N2,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = RPAD(   ';
      VSQL:=VSQL || '(SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 1)   ';
      VSQL:=VSQL || ')) || (SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL   ';
      VSQL:=VSQL || '= 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) ,   ';
      VSQL:=VSQL || 'LENGTH(MOV_CLAVE_INV), ''0'' )) AS NomN2,  ';
      VSQL:=VSQL || 'TO_NUMBER(SUBSTR(MOV_CLAVE_INV, (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
      VSQL:=VSQL || 'EST_NIVEL <= 2) )) AS N3,  ';
      VSQL:=VSQL || '(SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO = MOV_CONTRATO AND DAT_CLAVE = MOV_CLAVE_INV) AS   ';
      VSQL:=VSQL || 'NOMBRE,   ';
      VSQL:=VSQL || 'TO_CHAR(MOV_FEC_OPER,''DD/MM/YYYY'' ) AS MOV_FEC_OPER,  ';
      --VSQL:=VSQL || 'MOV_CLAVE_INV ,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''D'',MOV_IMPORTE,0),0) AS DEPOSITO,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''R'',MOV_IMPORTE,0),0) AS RETIRO ,  ';
      VSQL:=VSQL || 'NVL(DECODE(MOV_TIPO_OPER, ''I'',MOV_IMPORTE,0),0) AS INTERES ,  ';
      VSQL:=VSQL || 'MOV_CONTRATO,   ';
      VSQL:=VSQL || 'LENGTH(MOV_CLAVE_INV),NVL(MOV_ACUERDO,''N/A''),NVL(MOV_OFICIO,''N/A''),NVL(MOV_BENEFICIARIO,''N/A'')   ';
      VSQL:=VSQL || 'FROM   FID_MOV_CTAS_IND  ';
      VSQL:=VSQL || 'WHERE  MOV_CONTRATO = '||TO_CHAR(FIDEICOMISO);
      VSQL:=VSQL || 'AND    MOV_FEC_OPER BETWEEN TO_DATE('''||FECHAINICIAL||''',''DD/MM/YYYY'') AND TO_DATE('''||VFECHAFINAL||''',''DD/MM/YYYY'')  ';
      --VSQL:=VSQL || 'AND    MOV_TIPO_OPER <> ''I''';
      /*IF LENGTH(VPARTICIPACION) > 0 THEN
        VSQL:=VSQL || ' AND MOV_CLAVE_INV='''||VPARTICIPACION||'''';
      END IF;*/
      IF INSTR(N1,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
        VSQL:=VSQL || '= 1) ))=SUBSTR('''||N1||''', 1, (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL ';
        VSQL:=VSQL || '= 1) )';
      END IF;
      IF INSTR(N2,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )) =SUBSTR(''';
        VSQL:=VSQL || N2||''', (SELECT EST_LONG_ID + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL = 1), (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND EST_NIVEL = 2) )';
      END IF;
      IF INSTR(N3,'-1')=0 THEN
        VSQL:=VSQL || ' AND (SUBSTR(MOV_CLAVE_INV, (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL <= 2) ))=SUBSTR(''';
        VSQL:=VSQL || N3||''', (SELECT SUM(EST_LONG_ID) + 1 FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO = MOV_CONTRATO AND   ';
        VSQL:=VSQL || 'EST_NIVEL <= 2) )';
      END IF;

      IF LENGTH(OFICIO)>0 THEN
        VSQL:=VSQL || ' AND MOV_OFICIO LIKE ''%'||OFICIO||'%''';
      END IF;

      IF LENGTH(ACUERDO)>0 THEN
        VSQL:=VSQL || ' AND MOV_ACUERDO LIKE ''%'||ACUERDO||'%''';
      END IF;

      IF LENGTH(BENEFICIARIO)>0 THEN
        VSQL:=VSQL || ' AND MOV_BENEFICIARIO LIKE ''%'||BENEFICIARIO||'%''';
      END IF;

      OPEN RS_REPCTASIND FOR VSQL;

      DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'ARCHIVO',VSQL);
      LOOP
        FETCH RS_REPCTASIND INTO NRCI_NUM_N1,VRCI_NOM_N1,NRCI_NUM_N2,VRCI_NOM_N2,NRCI_NUM_N3,VRCI_NOM_INVERS,VRCI_FECHA,NRCI_DEPOSITOS,NRCI_RETIROS,
        NRCI_INTERESES,NRCI_NUM_FIDEICOMISO,NRCI_NUM_INVER,VACUERDO,VOFICIO,VBENEFICIARIO;
        EXIT WHEN RS_REPCTASIND%NOTFOUND;

          --SE OBTIENE EL SALDO ANTERIOR
          --PRIMERO SE OBTIENEN DEPOSITOS
          NRCI_SALDO_ANT:=0;
          SELECT SUM(MOV_IMPORTE) INTO NDEPOSITOSANTERIOR
          FROM fid_mov_ctas_ind
          WHERE
          MOV_CONTRATO=FIDEICOMISO AND
          MOV_CLAVE_INV=NRCI_NUM_N3 AND
          TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY')<TO_DATE(FECHAINICIAL,'DD/MM/YYYY') AND
          MOV_TIPO_OPER='D';
          --DESPUES SE OBTIENEN RETIROS
          SELECT SUM(MOV_IMPORTE) INTO NRETIROSANTERIOR
          FROM fid_mov_ctas_ind
          WHERE
          MOV_CONTRATO=FIDEICOMISO AND
          MOV_CLAVE_INV=NRCI_NUM_N3 AND
          TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY')<TO_DATE(FECHAINICIAL,'DD/MM/YYYY') AND
          MOV_TIPO_OPER='R';          

          --SE DETERMINAN INTERESES ANTERIORES
          SELECT SUM(MOV_IMPORTE) INTO NRETIROSANTERIOR
          FROM fid_mov_ctas_ind
          WHERE
          MOV_CONTRATO=FIDEICOMISO AND
          MOV_CLAVE_INV=NRCI_NUM_N3 AND
          TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY')<TO_DATE(FECHAINICIAL,'DD/MM/YYYY') AND
          MOV_TIPO_OPER='I';            

          NRCI_SALDO_ANT:=NVL(NDEPOSITOSANTERIOR,0)-NVL(NRETIROSANTERIOR,0)+NVL(NINTERESESANTERIOR,0);


          INSERT INTO REPCTAIND VALUES (
            NSECUENCIAL,FIDEICOMISO,VRCI_NOM_FIDEICOMISO,
            VRCI_PERIODO,--PERIODO
            VRCI_FECHA,
            NOMN1,--NOMBRE DE NIVEL 1
            NOMN2,--NOMBRE DE NIVEL 2
            NOMN3,--NOMBRE DE NIVEL 3
            VRCI_NOM_INVERS,
            NRCI_NUM_N1,NVL(NRCI_NUM_N2,0),NVL(NRCI_NUM_N3,0),
            VRCI_NOM_N1,VRCI_NOM_N2,
            0,--NUMERO DE INVERSIONISTAS
            NRCI_SALDO_ANT,--SALDO ANTERIOR
            0,--TASA
            NRCI_DEPOSITOS,NRCI_RETIROS,
            NRCI_INTERESES,--INTERESES
            0,--ISR
            0,--PARTICIPACION
            0,--SALDO PARCIAL
            NRCI_SALDO_ANT+NVL(NRCI_DEPOSITOS,0)-NVL(NRCI_RETIROS,0)+NVL(NRCI_INTERESES,0),
            VACUERDO,VOFICIO,VBENEFICIARIO---SALDO FINAL
          );
        NSECUENCIAL:=NSECUENCIAL+1;
      END LOOP;
      CLOSE RS_REPCTASIND;


    ELSIF TIPO = 9999 THEN --ESTADO DE CUENTA POR INVERSIONISTA

      DELETE FROM REPCTAIND WHERE RCI_NUM_N2=N2;
      DELETE FROM FID_RES_CTAS_IND WHERE SAL_CLAVE_INV=N2;

      PDT_INI := REPLACE('01'||SUBSTR(FECHAFINAL, 3, LENGTH(FECHAFINAL)),' ','');

      VRCI_PERIODO := PDT_INI || ' al ' || FECHAFINAL;      

      SELECT TRUNC(MONTHS_BETWEEN( FECHAFINAL,(SELECT DAT_FEC_ALTA FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_ID = N2)) / 12) INTO NANIOS FROM DUAL;

      IF NANIOS<29 THEN      
        SELECT DER_PCJ INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
      ELSE
        NPORCENTAJE:=1;
      END IF;

     /* IF NPORCENTAJE=0 THEN
        NPORCENTAJE:=100;
      END IF;*/

      --SE EJECUTA EL PROCEDIMIENTO QUE DETERMINA LOS SALDOS PARA EL INVERSIONISTA EN CUESTION
      --DELETE FID_RES_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO and SAL_CLAVE_INV=N2;
      INSERT INTO FID_RES_CTAS_IND
      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'SA' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3,5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') < TO_DATE(PDT_INI,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'D' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER BETWEEN PDT_INI AND FECHAFINAL
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'R' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER BETWEEN PDT_INI AND FECHAFINAL
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'I' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER BETWEEN PDT_INI AND FECHAFINAL
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'S' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,--TO_CHAR(NPORCENTAJE,'000') || '%',
        'DA' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * NPORCENTAJE / 100
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * NPORCENTAJE / 100            
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000') || '%',NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE  MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO;

      SELECT 
        NVL(SUM(
        CASE 
          WHEN MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
          WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
          ELSE 0
        END), 0) INTO NPARTICIPACION
      FROM FID_MOV_CTAS_IND
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER < PDT_INI
      ORDER BY MOV_FEC_OPER, MOV_SECUENCIAL;

        VSQL:= '
            SELECT 
              MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = ''D'' THEN ''DepÃ³sito Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = ''D'' THEN ''DepÃ³sito H. Ayuntamiento''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''Interes Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''Interes H. Ayuntamiento''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = ''R'' THEN ''Retiro Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = ''R'' THEN ''Retiro H. Ayuntamiento''
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN MOV_IMPORTE
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN MOV_IMPORTE
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND
              MOV_FEC_OPER BETWEEN ''' || PDT_INI || ''' AND ''' || FECHAFINAL || '''
            ORDER BY MOV_FEC_OPER, MOV_SECUENCIAL';

        OPEN RS_REPCTASIND2 FOR VSQL;
        LOOP
          FETCH RS_REPCTASIND2 INTO VRCI_FECHA,VDATOS,NRCI_DEPOSITOS,NRCI_RETIROS;

          EXIT WHEN RS_REPCTASIND2%NOTFOUND;

          NPARTICIPACION:= NPARTICIPACION + NRCI_DEPOSITOS - NRCI_RETIROS;

          IF NRCI_DEPOSITOS<>0 OR NRCI_RETIROS<>0 THEN
            INSERT INTO REPCTAIND VALUES (
              NSECUENCIAL,
              FIDEICOMISO,
              VRCI_NOM_FIDEICOMISO,
              VRCI_PERIODO,--PERIODO
              VRCI_FECHA,
              NOMN1,--NOMBRE DE NIVEL 1
              NOMN2,--NOMBRE DE NIVEL 2
              NOMN3,--NOMBRE DE NIVEL 3
              VDATOS,
              N1,
              N2,
              N3,
              (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
              (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
              0,--NUMERO DE INVERSIONISTAS
              NPARTICIPACION,--SALDO ANTERIOR
              NRCI_TASA,
              NRCI_DEPOSITOS,
              NRCI_RETIROS,
              NRCI_INTERESES,--INTERESES
              NRCI_ISR,--ISR
              NPARTICIPACION,--SALDO PARCIAL
              NULL,--PARTICIPACION
              NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
            );
          END IF;        
        NSECUENCIAL := NSECUENCIAL + 1;
      END LOOP;
      CLOSE RS_REPCTASIND2;

     /* SELECT COUNT(1) INTO NDATOS
      FROM FID_RES_CTAS_IND WHERE ID='SA';
      IF NDATOS=0 THEN
        INSERT INTO FID_RES_CTAS_IND VALUES (PDT_INI,FIDEICOMISO,N2,'SA',0,0,0);
      END IF;*/
    ELSIF TIPO = 2 OR TIPO=7 OR TIPO=9 THEN --ESTADO DE CUENTA POR INVERSIONISTA ALTA

      SELECT NVL(DAT_FEC_BAJA,''),NVL(DAT_FEC_ALTA,'') INTO FECHABAJA,FECHAALTA
      FROM fid_datos_est_ctas
      WHERE 
      DAT_CLAVE=N2 and
      DAT_CONTRATO=FIDEICOMISO;
      --FECHAFINAL:=FECHAALTA;
      /*IF LENGTH(FECHABAJA)>0 AND FECHABAJA<>NULL THEN
        IF FECHABAJA<FECHAFINAL THEN
          FECHAFINAL:=FECHABAJA;
        END IF;
      END IF;*/
      IF NVL(OFICIO,'NULO')<>'MASIVO' THEN
       DELETE FROM REPCTAIND WHERE RCI_NUM_N2=N2;
        DELETE FROM FID_RES_CTAS_IND WHERE SAL_CLAVE_INV=N2;
      END IF;
      PDT_INI := REPLACE('01'||SUBSTR(FECHAFINAL, 3, LENGTH(FECHAFINAL)),' ','');

      IF TIPO=2 THEN
        VRCI_PERIODO := PDT_INI || ' al ' || FECHAFINAL;      
      ELSE
        VRCI_PERIODO := FECHAINICIAL || ' al ' || FECHAFINAL;      
      END IF;
      /*DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'ARCHIVO',FECHABAJA);
      COMMIT;
      IF NVL(FECHABAJA,'VACIO')<>'VACIO' THEN
        FECHAFINAL:=TO_CHAR(FECHABAJA,'DD/MM/YYYY');
      END IF; 
      */
      IF NVL(FECHAINICIAL,'VACIO')<>'VACIO'  AND TIPO=2 THEN
        SELECT TRUNC(MONTHS_BETWEEN( TO_DATE(FECHAINICIAL,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
      ELSE
          --MODIFICACION DEL 05/06/2023
          IF NVL(TO_CHAR(FECHABAJA,'DD/MM/YYYY'),'01/01/1900')<>'01/01/1900' THEN
            SELECT TRUNC(MONTHS_BETWEEN(FECHABAJA, FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            --INSERT INTO ARCHIVOS_PLANOS VALUES (2, SYSDATE,'ARCHIVO',FECHABAJA);
          ELSE
            --SELECT TRUNC(MONTHS_BETWEEN(TO_DATE(FECHA_CORTE,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            SELECT TRUNC(MONTHS_BETWEEN( TO_DATE(FECHAFINAL,'DD/MM/YYYY'),FECHAALTA) / 12) INTO NANIOS FROM DUAL;
            --INSERT INTO ARCHIVOS_PLANOS VALUES (2, SYSDATE,'ARCHIVO',FECHA_CORTE);
          END IF;
      END IF;

      /*IF NANIOS<29 THEN      
        SELECT DER_PCJ INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
      ELSE
        NPORCENTAJE:=0;
      END IF;*/


      IF NANIOS<29 THEN      
        SELECT COUNT(1) INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);

        IF NPORCENTAJE>0 THEN
          SELECT DER_PCJ INTO NPORCENTAJE
          FROM FID_DER_ADQ
          WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
        ELSE
          NPORCENTAJE:=1;
        END IF;  
      ELSE
        NPORCENTAJE:=1;
      END IF;
     /* IF NPORCENTAJE=0 THEN
        NPORCENTAJE:=100;
      END IF;*/

      --SE EJECUTA EL PROCEDIMIENTO QUE DETERMINA LOS SALDOS PARA EL INVERSIONISTA EN CUESTION
      --DELETE FID_RES_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO and SAL_CLAVE_INV=N2;
      /*DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'ARCHIVO',NPORCENTAJE);
      COMMIT;*/

      INSERT INTO FID_RES_CTAS_IND
      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'SA' ID,
        0 TRABAJADOR,
        0 AYUNTAMIENTO,
        TO_NUMBER(
        TO_CHAR((NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3,5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0)-
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3,5,6) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0)),'999,999,999,999,990.00'),'999,999,999,999,990.00') TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER < TO_DATE(FECHAINICIAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'D' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'R' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'I' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE*-1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'S' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,--TO_CHAR(NPORCENTAJE,'000') || '%',
        'DA' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * (NPORCENTAJE/100)
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,            
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'R' THEN (MOV_IMPORTE*-1) * (NPORCENTAJE/100)
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'999.99') || '%',NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE  MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        --TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
        MOV_FEC_OPER <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO;

      IF TIPO=2 THEN
        UPDATE FID_RES_CTAS_IND SET
        SAL_TOTAL=0
        WHERE
        SAL_CONTRATO=FIDEICOMISO AND
        SAL_CLAVE_INV=N2 AND
        ID='SA';
      END IF;

      IF TIPO=2 THEN  
        VSQL:= '
            SELECT 
              MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN MOV_IMPORTE
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN MOV_IMPORTE
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND';
      ELSIF TIPO=7 THEN
        VSQL:= '
            SELECT '''||FECHAFINAL|| 
                ''' MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN SUM(MOV_IMPORTE)
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN SUM(MOV_IMPORTE)
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND';
      ELSE--PARA EL CASO DE ESTADO DE CUENTA CON SUBRANGO        
        IF SUBRANGO='BIMESTRE' THEN
            VSQL:= 'SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
                CASE
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN ''BIMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN ''BIMESTRE 2''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN ''BIMESTRE 3''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN ''BIMESTRE 4'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN ''BIMESTRE 5''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN ''BIMESTRE 6''
                END AS PERIODO,
                SUM
                (
                CASE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN MOV_IMPORTE ELSE 0
                END) AS DEPOSITOS,
                SUM
                (
                CASE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN MOV_IMPORTE
                WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN MOV_IMPORTE ELSE 0
                END) AS RETIROS,            
                  CASE 
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                    WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                    ELSE MOV_OFICIO
                  END DESCRIPCION';
        ELSIF SUBRANGO='TRIMESTRE' THEN
            VSQL:= 'SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN ''TRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN ''TRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN ''TRIMESTRE 3''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN ''TRIMESTRE 4''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='CUATRIMESTRE' THEN    
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN ''CUATRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN ''CUATRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN ''CUATRIMESTRE 3''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='SEMESTRE' THEN
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN ''SEMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN ''SEMESTRE 2''
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        ELSIF SUBRANGO='ANUAL' THEN      
            VSQL:='SELECT TO_CHAR(EXTRACT(YEAR FROM MOV_FEC_OPER)) AS ANIO,
            CASE
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN ''ANUAL'' 
            END AS PERIODO,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''D'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS DEPOSITOS,
            SUM
            (
            CASE
            WHEN MOV_TIPO_OPER = ''R'' AND EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN MOV_IMPORTE ELSE 0
            END) AS RETIROS,            
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''INTERES H. AYUNTAMIENTO''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES TRABAJADOR''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''INTERES H. AYUNTAMIENTO''   
                ELSE MOV_OFICIO
              END DESCRIPCION';
        END IF;
        VSQL:=VSQL||' FROM FID_MOV_CTAS_IND
        WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9)';
      END IF;
      IF TIPO=2 THEN
        VSQL:=VSQL||' MOV_FEC_OPER <= ''' || FECHAFINAL || '''';
        VSQL:= VSQL||' ORDER BY 1,2';            
      ELSIF TIPO=7 THEN
        VSQL:=VSQL||' MOV_FEC_OPER BETWEEN ''' || FECHAINICIAL || ''' AND '''||FECHAFINAL||'''';
        VSQL:= VSQL||' GROUP BY MOV_CLAV
        E_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 2';
      ELSE
        VSQL:=VSQL||' AND MOV_FEC_OPER BETWEEN ''' || FECHAINICIAL || ''' AND '''||FECHAFINAL||'''';
        IF SUBRANGO='BIMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 2 THEN ''BIMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 3 AND 4 THEN ''BIMESTRE 2''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 6 THEN ''BIMESTRE 3''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 8 THEN ''BIMESTRE 4'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 10 THEN ''BIMESTRE 5''
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 11 AND 12 THEN ''BIMESTRE 6''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                ORDER BY 1,2,5';
        ELSIF SUBRANGO='TRIMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 3 THEN ''TRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 4 AND 6 THEN ''TRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 9 THEN ''TRIMESTRE 3''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 10 AND 12 THEN ''TRIMESTRE 4''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                ORDER BY 1,2,5';
        ELSIF SUBRANGO='CUATRIMESTRE' THEN        
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 4 THEN ''CUATRIMESTRE 1'' 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 5 AND 8 THEN ''CUATRIMESTRE 2''
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 9 AND 12 THEN ''CUATRIMESTRE 3''
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 1,2,5';
        ELSIF SUBRANGO='SEMESTRE' THEN
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                    CASE 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 6 THEN ''SEMESTRE 1'' 
                    WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 7 AND 12 THEN ''SEMESTRE 2''
                    END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                           ORDER BY 1,2,5';
        ELSIF SUBRANGO='ANUAL' THEN      
            VSQL:=VSQL||' GROUP BY EXTRACT(YEAR FROM MOV_FEC_OPER),
                CASE 
                WHEN EXTRACT(MONTH FROM MOV_FEC_OPER) BETWEEN 1 AND 12 THEN ''ANUAL'' 
                END,MOV_CLAVE_INV,MOV_TIPO_OPER,MOV_OFICIO
                       ORDER BY 1,2,5';        
        END IF;
      END IF;

        OPEN RS_REPCTASIND2 FOR VSQL;
        LOOP
          NRCI_DEPOSITOS:=0;
          NRCI_RETIROS:=0;
          IF TIPO=9 THEN
            FETCH RS_REPCTASIND2 INTO VRCI_FECHA_ANIO,VRCI_FECHA_PERIODO,NRCI_DEPOSITOS,NRCI_RETIROS,VDATOS;
          ELSE
            FETCH RS_REPCTASIND2 INTO VRCI_FECHA,VDATOS,NRCI_DEPOSITOS,NRCI_RETIROS;
          END IF;

          EXIT WHEN RS_REPCTASIND2%NOTFOUND;

          NPARTICIPACION:= NPARTICIPACION + NRCI_DEPOSITOS - NRCI_RETIROS;

          IF TIPO=9 THEN
            VRCI_FECHA:=VRCI_FECHA_PERIODO||' '||VRCI_FECHA_ANIO;  
          END IF;  

          IF NRCI_DEPOSITOS<>0 OR NRCI_RETIROS<>0 THEN
            IF TIPO=2 THEN                            
                INSERT INTO REPCTAIND VALUES (
                  NSECUENCIAL,
                  FIDEICOMISO,
                  VRCI_NOM_FIDEICOMISO,
                  VRCI_PERIODO,--PERIODO
                  VRCI_FECHA,
                  NOMN1,--NOMBRE DE NIVEL 1
                  NOMN2,--NOMBRE DE NIVEL 2
                  NOMN3,--NOMBRE DE NIVEL 3
                  VDATOS,
                  N1,
                  N2,
                  N3,
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                  0,--NUMERO DE INVERSIONISTAS
                  NPARTICIPACION,--SALDO ANTERIOR
                  NRCI_TASA,
                  NRCI_DEPOSITOS,
                  NRCI_RETIROS,
                  NRCI_INTERESES,--INTERESES
                  NRCI_ISR,--ISR
                  NPARTICIPACION,--SALDO PARCIAL
                  TIPO,--TIPO ESTADO DE CUENTA
                  NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                );
            ELSIF TIPO= 7 THEN
                --PARA EL CASO DE INTERESES SE DESCARTAN LOS RETIROS
                IF INSTR(VDATOS,'INTERES')>0 THEN
                    NRCI_DEPOSITOS:= NRCI_DEPOSITOS - NRCI_RETIROS;
                    NRCI_RETIROS:=0;
                END IF;

                SELECT COUNT(1) INTO NDATOS 
                FROM REPCTAIND
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_NOM_INVERS=VDATOS AND
                RCI_NUM_N2=N2;

                IF NDATOS=0 THEN
                    INSERT INTO REPCTAIND VALUES (
                      NSECUENCIAL,
                      FIDEICOMISO,
                      VRCI_NOM_FIDEICOMISO,
                      VRCI_PERIODO,--PERIODO
                      VRCI_FECHA,
                      NOMN1,--NOMBRE DE NIVEL 1
                      NOMN2,--NOMBRE DE NIVEL 2
                      NOMN3,--NOMBRE DE NIVEL 3
                      VDATOS,
                      N1,
                      N2,
                      N3,
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                      0,--NUMERO DE INVERSIONISTAS
                      NPARTICIPACION,--SALDO ANTERIOR
                      NRCI_TASA,
                      NRCI_DEPOSITOS,
                      NRCI_RETIROS,
                      NRCI_INTERESES,--INTERESES
                      NRCI_ISR,--ISR
                      NPARTICIPACION,--SALDO PARCIAL
                      TIPO,--TIPO ESTADO DE CUENTA
                      NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                    );
                ELSE
                    UPDATE REPCTAIND SET
                    RCI_DEPOSITOS=RCI_DEPOSITOS+NRCI_DEPOSITOS,
                    RCI_RETIROS=RCI_RETIROS+NRCI_RETIROS
                    WHERE
                    RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                    RCI_NOM_INVERS=VDATOS AND
                    RCI_NUM_N2=N2;                   
                END IF;
            ELSE  
                --PARA EL CASO DE INTERESES SE DESCARTAN LOS RETIROS
                IF INSTR(VDATOS,'INTERES')>0 THEN
                    NRCI_DEPOSITOS:= NRCI_DEPOSITOS - NRCI_RETIROS;
                    NRCI_RETIROS:=0;
                END IF;

                SELECT COUNT(1) INTO NDATOS 
                FROM REPCTAIND
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_NOM_INVERS=VDATOS AND
                RCI_NUM_N2=N2 AND
                RCI_FECHA=VRCI_FECHA;

                IF NDATOS=0 THEN
                    INSERT INTO REPCTAIND VALUES (
                      NSECUENCIAL,
                      FIDEICOMISO,
                      VRCI_NOM_FIDEICOMISO,
                      VRCI_PERIODO,--PERIODO
                      VRCI_FECHA,
                      NOMN1,--NOMBRE DE NIVEL 1
                      NOMN2,--NOMBRE DE NIVEL 2
                      NOMN3,--NOMBRE DE NIVEL 3
                      VDATOS,
                      N1,
                      N2,
                      N3,
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                      (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                      0,--NUMERO DE INVERSIONISTAS
                      NPARTICIPACION,--SALDO ANTERIOR
                      NRCI_TASA,
                      NRCI_DEPOSITOS,
                      NRCI_RETIROS,
                      NRCI_INTERESES,--INTERESES
                      NRCI_ISR,--ISR
                      NPARTICIPACION,--SALDO PARCIAL
                      TIPO,--TIPO ESTADO DE CUENTA
                      NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                    );
                ELSE
                    UPDATE REPCTAIND SET
                    RCI_DEPOSITOS=RCI_DEPOSITOS+NRCI_DEPOSITOS,
                    RCI_RETIROS=RCI_RETIROS+NRCI_RETIROS
                    WHERE
                    RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                    RCI_NOM_INVERS=VDATOS AND
                    RCI_NUM_N2=N2 AND
                    RCI_FECHA=VRCI_FECHA;                   
                END IF;           
            END IF;
          END IF;        

        NSECUENCIAL := NSECUENCIAL + 1;
      END LOOP;
      CLOSE RS_REPCTASIND2;

        OPEN RS_REPCTASIND2 FOR 
        SELECT RCI_SECUENCIAL,RCI_FECHA,RCI_DEPOSITOS,RCI_RETIROS 
        FROM REPCTAIND
        WHERE RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
        RCI_NUM_N2=N2
        ORDER BY RCI_SECUENCIAL ASC;
        LOOP
            FETCH RS_REPCTASIND2 INTO NSECUENCIAL,VRCI_FECHA_ANIO,NRCI_DEPOSITOS,NRCI_RETIROS;
            EXIT WHEN RS_REPCTASIND2%NOTFOUND;
            IF NRCI_DEPOSITOS<0 THEN
                NRCI_RETIROS:=NRCI_DEPOSITOS*-1;
                NRCI_DEPOSITOS:=0;

                UPDATE REPCTAIND SET
                RCI_DEPOSITOS=NRCI_DEPOSITOS,
                RCI_RETIROS=NRCI_RETIROS
                WHERE
                RCI_NUM_FIDEICOMISO=FIDEICOMISO AND
                RCI_SECUENCIAL=NSECUENCIAL AND
                RCI_FECHA=VRCI_FECHA_ANIO AND
                RCI_NUM_N2=N2;               
            END IF;
        END LOOP;
        CLOSE RS_REPCTASIND2;

     /* SELECT COUNT(1) INTO NDATOS
      FROM FID_RES_CTAS_IND WHERE ID='SA';
      IF NDATOS=0 THEN
        INSERT INTO FID_RES_CTAS_IND VALUES (PDT_INI,FIDEICOMISO,N2,'SA',0,0,0);
      END IF;*/
    ELSIF TIPO = 8 THEN --ESTADO DE CUENTA POR INVERSIONISTA BAJA
      FECHAFINAL:=VFECHAFINAL;
      VRCI_PERIODO:=FECHAINICIAL||' AL '||FECHAFINAL;      
      DELETE FROM REPCTAIND WHERE RCI_NUM_N2=N2;
      DELETE FROM FID_RES_CTAS_IND WHERE SAL_CLAVE_INV=N2;


      SELECT NVL(DAT_FEC_BAJA,TO_DATE('01/01/1900','DD/MM/YYYY')),
      NVL(DAT_FEC_ALTA,TO_DATE('01/01/1900','DD/MM/YYYY')) INTO FECHABAJA,FECHAALTA
      --SELECT NVL(DAT_FEC_BAJA,NVL(DAT_FEC_ALTA,TO_DATE('01/01/1900','DD/MM/YYYY'))),NVL(DAT_FEC_ALTA,TO_DATE('01/01/1900','DD/MM/YYYY')) INTO FECHABAJA,FECHAALTA
      FROM fid_datos_est_ctas
      WHERE 
      DAT_CLAVE=N2 and
      DAT_CONTRATO=FIDEICOMISO;

     /* IF FECHABAJA<>NULL AND TO_CHAR(FECHABAJA,'DD/MM/YYYY')<>'01/01/1900' THEN
        --FECHABAJA:='01/01/1900';
        FECHAFINAL:=TO_CHAR(FECHABAJA,'DD/MM/YYYY');
      END IF;*/
      --FECHABAJA:='01/01/1900';
      --FECHAFINAL:=FECHABAJA;
      /*IF LENGTH(FECHABAJA)>0 AND FECHABAJA<>NULL THEN
        IF FECHABAJA<FECHAFINAL THEN
          FECHAFINAL:=FECHABAJA;
        END IF;
      END IF;*/

/*      DELETE FROM REPCTAIND WHERE RCI_NUM_N2=N2;
      DELETE FROM FID_RES_CTAS_IND WHERE SAL_CLAVE_INV=N2;

      PDT_INI := REPLACE('01'||SUBSTR(FECHAFINAL, 3, LENGTH(FECHAFINAL)),' ','');

      VRCI_PERIODO := PDT_INI || ' al ' || FECHAFINAL;      */

      SELECT ABS(TRUNC(MONTHS_BETWEEN(FECHAALTA,FECHABAJA)/ 12) ) INTO NANIOS FROM DUAL;
      DELETE FROM ARCHIVOS_PLANOS;
      INSERT INTO ARCHIVOS_PLANOS VALUES (1,SYSDATE,'BAJA ARCHIVO',FECHAALTA||'-'||FECHABAJA||'-'||NANIOS||' FECHA FINAL:'||FECHAFINAL);

      IF NANIOS<29 THEN      
        SELECT DER_PCJ INTO NPORCENTAJE
        FROM FID_DER_ADQ
        WHERE DER_ANT = DECODE(NANIOS, NULL, 1, 0, 1, NANIOS);      
      ELSE
        NPORCENTAJE:=0;
      END IF;

     /* IF NPORCENTAJE=0 THEN
        NPORCENTAJE:=100;
      END IF;*/

      --SE EJECUTA EL PROCEDIMIENTO QUE DETERMINA LOS SALDOS PARA EL INVERSIONISTA EN CUESTION
      --DELETE FID_RES_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO and SAL_CLAVE_INV=N2;

      INSERT INTO FID_RES_CTAS_IND
      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'SA' ID,
        0 TRABAJADOR,
        0 AYUNTAMIENTO,
        0 TOTAL,TO_CHAR(NPORCENTAJE,'000.00'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) 
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'D' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(1,3) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000.00'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9) AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'R' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000.00'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'I' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) IN(5,6) AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000.00'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,
        'S' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE
            WHEN MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000.00'),NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO

      UNION ALL 

      SELECT 
        TO_DATE(VFECHAFINAL,'DD/MM/YYYY'),
        FIDEICOMISO,
        N2,--TO_CHAR(NPORCENTAJE,'000') || '%',
        'DA' ID,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            ELSE 0
          END)
        ,0) TRABAJADOR,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * NPORCENTAJE / 100
            ELSE 0
          END)
        ,0) AYUNTAMIENTO,
        NVL(SUM(
          CASE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = 'D' THEN MOV_IMPORTE * NPORCENTAJE / 100
            WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = 'R' THEN MOV_IMPORTE * -1 * NPORCENTAJE / 100            
            ELSE 0
          END)
        , 0) TOTAL,TO_CHAR(NPORCENTAJE,'000.00') || '%',NANIOS
      FROM FID_MOV_CTAS_IND 
      WHERE  MOV_CONTRATO = FIDEICOMISO AND 
        SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR(N2,1,9)  AND
        TO_DATE(TO_CHAR(MOV_FEC_OPER,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE(FECHAFINAL,'DD/MM/YYYY')
      GROUP BY MOV_CONTRATO;

        VSQL:= '
            SELECT 
              MOV_FEC_OPER,
              CASE 
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = ''D'' THEN ''DepÃ³sito Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = ''D'' THEN ''DepÃ³sito H. Ayuntamiento''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''D'' THEN ''Interes Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''D'' THEN ''Interes H. Ayuntamiento''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 1 AND MOV_TIPO_OPER = ''R'' THEN ''Retiro Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 3 AND MOV_TIPO_OPER = ''R'' THEN ''Retiro H. Ayuntamiento''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 5 AND MOV_TIPO_OPER = ''R'' THEN ''Interes Trabajador''
                WHEN SUBSTR(MOV_CLAVE_INV,10,1) = 6 AND MOV_TIPO_OPER = ''R'' THEN ''Interes H. Ayuntamiento''                
              END DESCRIPCION,
              CASE 
                WHEN MOV_TIPO_OPER = ''D'' THEN MOV_IMPORTE
                ELSE 0
              END DEPOSITOS,
              CASE 
                WHEN MOV_TIPO_OPER = ''R'' THEN MOV_IMPORTE
                ELSE 0
              END RETIROS
            FROM FID_MOV_CTAS_IND
            WHERE MOV_CONTRATO = ' || TO_CHAR(FIDEICOMISO) || ' AND 
              SUBSTR(MOV_CLAVE_INV,1,9) = SUBSTR('''|| N2 ||''',1,9) AND
              MOV_FEC_OPER <= ''' || FECHAFINAL || '''
            ORDER BY MOV_FEC_OPER, MOV_SECUENCIAL';

      INSERT INTO ARCHIVOS_PLANOS VALUES (2,SYSDATE,'BAJA ARCHIVO',FECHAALTA||'-'||FECHABAJA||'-'||NANIOS||' FECHA FINAL:'||FECHAFINAL);
      INSERT INTO ARCHIVOS_PLANOS VALUES (3,SYSDATE,'BAJA ARCHIVO',VSQL);
      COMMIT;

        OPEN RS_REPCTASIND2 FOR VSQL;
        LOOP
          FETCH RS_REPCTASIND2 INTO VRCI_FECHA,VDATOS,NRCI_DEPOSITOS,NRCI_RETIROS;

          EXIT WHEN RS_REPCTASIND2%NOTFOUND;

          NPARTICIPACION:= NPARTICIPACION + NRCI_DEPOSITOS - NRCI_RETIROS;

          IF NRCI_DEPOSITOS<>0 OR NRCI_RETIROS<>0 THEN
                INSERT INTO REPCTAIND VALUES (
                  NSECUENCIAL,
                  FIDEICOMISO,
                  VRCI_NOM_FIDEICOMISO,
                  VRCI_PERIODO,--PERIODO
                  VRCI_FECHA,
                  NOMN1,--NOMBRE DE NIVEL 1
                  NOMN2,--NOMBRE DE NIVEL 2
                  NOMN3,--NOMBRE DE NIVEL 3
                  VDATOS,
                  N1,
                  N2,
                  N3,
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 1 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N1),
                  (SELECT DAT_DATO FROM FID_DATOS_EST_CTAS WHERE DAT_NIVEL = 2 AND DAT_CONTRATO = FIDEICOMISO AND DAT_CLAVE = N2),
                  0,--NUMERO DE INVERSIONISTAS
                  NPARTICIPACION,--SALDO ANTERIOR
                  NRCI_TASA,
                  NRCI_DEPOSITOS,
                  NRCI_RETIROS,
                  NRCI_INTERESES,--INTERESES
                  NRCI_ISR,--ISR
                  NPARTICIPACION,--SALDO PARCIAL
                  NULL,--PARTICIPACION
                  NPARTICIPACION,'N/A','N/A','N/A'--SALDO FINAL
                );
          END IF;        
        NSECUENCIAL := NSECUENCIAL + 1;
      END LOOP;
      CLOSE RS_REPCTASIND2;

     /* SELECT COUNT(1) INTO NDATOS
      FROM FID_RES_CTAS_IND WHERE ID='SA';
      IF NDATOS=0 THEN
        INSERT INTO FID_RES_CTAS_IND VALUES (PDT_INI,FIDEICOMISO,N2,'SA',0,0,0);
      END IF;*/

    ELSIF TIPO = 3 THEN--RESUMEN POR NIVEL 1

      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      IF INSTR(N1,'-1')=0 THEN
        SELECT DISTINCT DAT_CLAVE INTO VN1
        FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO=FIDEICOMISO AND DAT_ID=N1;
      END IF;
      --SE ELIMINAN LAS TABLAS TEMPORALES
      DELETE FROM FID_SAL_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO;
      DELETE FROM FID_SAL_CTAS_IND_ACUM WHERE SAL_CONTRATO = FIDEICOMISO;
      SELECT SUBSTR(N1, 1,
      (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO =
      FIDEICOMISO AND EST_NIVEL = 1)) INTO PN_NIVEL FROM DUAL;

      --SE DETERMINA LOS VALORES MINIMO Y MAXIMO DE LOS NIVELES DE INVERSIONISTAS PROPORCIONADOS
      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      SELECT DISTINCT MIN(TO_NUMBER(DAT_CLAVE)),MAX(TO_NUMBER(DAT_CLAVE)) INTO VMININV,VMAXINV
      FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO=FIDEICOMISO AND DAT_CLAVE LIKE PN_NIVEL||'%';

      VSQL := 'SELECT  ';
      VSQL := VSQL ||  'MOV_CONTRATO AS MOV_CONTRATO,  ';
      VSQL := VSQL ||  'SUBSTR(MOV_CLAVE_INV,1,EST_LONG_ID) AS N1,  ';
      VSQL := VSQL ||  'DAT_DATO AS NomN1,  ';
      VSQL := VSQL ||  'SUM(0) AS SALDO_INI,  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''D'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''R'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0) as cuenta,  ';
      VSQL := VSQL ||  'SUM(0) AS SAL_PARCIAL,  ';
      VSQL := VSQL ||  '0 PARTICIPACION  ';
      VSQL := VSQL ||  'FROM  FID_MOV_CTAS_IND, ';
      VSQL := VSQL ||  'FID_DATOS_EST_CTAS,  ';
      VSQL := VSQL ||  'FID_ESTRUC_CTAS_IND  ';
      VSQL := VSQL ||  'WHERE ';
      VSQL := VSQL ||  'DAT_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  'DAT_CLAVE=MOV_CLAVE_INV AND  ';
      VSQL := VSQL ||  'EST_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  ' MOV_CONTRATO='||TO_CHAR(FIDEICOMISO);
      VSQL := VSQL ||  ' AND EST_NIVEL= '||TO_CHAR(1);
      VSQL := VSQL ||  ' AND SUBSTR(MOV_CLAVE_INV,1,2)= '|| SUBSTR(N1,1,2);
      VSQL := VSQL ||  ' GROUP BY  ';
      VSQL := VSQL ||  'MOV_CONTRATO,MOV_CLAVE_INV,EST_LONG_ID,DAT_DATO  ';
      VSQL := VSQL ||  'ORDER BY   ';
      VSQL := VSQL ||  'MOV_CONTRATO,N1  ';
      OPEN RS_REPCTASIND FOR VSQL;
      LOOP
        FETCH RS_REPCTASIND INTO NRCI_NUM_FIDEICOMISO,NRCI_NUM_N1,VRCI_NOM_N1,
                                 NRCI_SALDO_ANT, NRCI_DEPOSITOS,NRCI_RETIROS,
                                 NRCI_INTERESES,NRCI_ISR,NRCI_TASA,NRCI_SALDO_FINAL,NPORCPARTICIPA;
        EXIT WHEN RS_REPCTASIND%NOTFOUND;
          --IF NPORCPARTICIPA > 0 THEN
            NPARTICIPACION:=0;
          --END IF;


          INSERT INTO REPCTAIND VALUES (
            NSECUENCIAL,NRCI_NUM_FIDEICOMISO,VRCI_NOM_FIDEICOMISO,
            VRCI_PERIODO,--PERIODO
            VFECHAFINAL,--FECHA
            NOMN1,--NOMBRE DE NIVEL 1
            NOMN2,--NOMBRE DE NIVEL 2
            NOMN3,--NOMBRE DE NIVEL 3
            '',--NOMBRE DEL INVERSIONISTA
            NRCI_NUM_N1,NVL(NRCI_NUM_N2,0),0,
            VRCI_NOM_N1,NVL(VRCI_NOM_N2,'N2'),
            NRCI_TASA,--NUMERO DE INVERSIONISTAS
            NRCI_SALDO_ANT,--SALDO ANTERIOR
            NRCI_TASA,
            NRCI_DEPOSITOS,NRCI_RETIROS,
            NRCI_INTERESES,--INTERESES
            NRCI_ISR,--ISR
            0,--SALDO PARCIAL
            NPARTICIPACION,--PARTICIPACION
            NRCI_SALDO_FINAL,'N/A','N/A','N/A'--SALDO FINAL
          );

        EXIT WHEN RS_REPCTASIND%NOTFOUND;
        NSECUENCIAL:=NSECUENCIAL+1;
      END LOOP;
      CLOSE RS_REPCTASIND;


    ELSIF TIPO = 4 THEN--RESUMEN POR NIVEL 2

      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      IF INSTR(N1,'-1')=0 THEN
        SELECT DISTINCT DAT_CLAVE INTO VN1
        FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO=FIDEICOMISO AND DAT_ID=N1;
      END IF;
      --SE DETERMINA LOS VALORES MINIMO Y MAXIMO DE LOS NIVELES DE INVERSIONISTAS PROPORCIONADOS
      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      SELECT DISTINCT MIN(TO_NUMBER(DAT_CLAVE)),MAX(TO_NUMBER(DAT_CLAVE)) INTO VMININV,VMAXINV
      FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO=FIDEICOMISO AND DAT_CLAVE LIKE PN_NIVEL||'%';

      VSQL := 'SELECT  ';
      VSQL := VSQL ||  'MOV_CONTRATO AS MOV_CONTRATO,  ';
      VSQL := VSQL ||  'SUBSTR(MOV_CLAVE_INV,1,EST_LONG_ID) AS N1,  ';
      VSQL := VSQL ||  'DAT_DATO AS NomN1,  ';
      VSQL := VSQL ||  'SUBSTR(MOV_CLAVE_INV,1,EST_LONG_ID) AS N2,  ';
      VSQL := VSQL ||  'DAT_DATO AS NomN2,  ';      
      VSQL := VSQL ||  'SUM(0) AS SALDO_INI,  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''D'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''R'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0) as cuenta,  ';
      VSQL := VSQL ||  'SUM(0) AS SAL_PARCIAL,  ';
      VSQL := VSQL ||  '0 PARTICIPACION  ';
      VSQL := VSQL ||  'FROM  FID_MOV_CTAS_IND, ';
      VSQL := VSQL ||  'FID_DATOS_EST_CTAS,  ';
      VSQL := VSQL ||  'FID_ESTRUC_CTAS_IND  ';
      VSQL := VSQL ||  'WHERE ';
      VSQL := VSQL ||  'DAT_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  'DAT_CLAVE=MOV_CLAVE_INV AND  ';
      VSQL := VSQL ||  'EST_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  ' MOV_CONTRATO='||TO_CHAR(FIDEICOMISO);
      VSQL := VSQL ||  ' AND EST_NIVEL= '||TO_CHAR(2);
      VSQL := VSQL ||  ' AND SUBSTR(MOV_CLAVE_INV,3,3)= '|| SUBSTR(N2,3,3);
      VSQL := VSQL ||  ' GROUP BY  ';
      VSQL := VSQL ||  'MOV_CONTRATO,MOV_CLAVE_INV,EST_LONG_ID,DAT_DATO  ';
      VSQL := VSQL ||  'ORDER BY   ';
      VSQL := VSQL ||  'MOV_CONTRATO,N1  ';
      OPEN RS_REPCTASIND FOR VSQL;
      LOOP
        FETCH RS_REPCTASIND INTO NRCI_NUM_FIDEICOMISO,NRCI_NUM_N1,VRCI_NOM_N1,NRCI_NUM_N2,VRCI_NOM_N2,
                                 NRCI_SALDO_ANT, NRCI_DEPOSITOS,NRCI_RETIROS,
                                 NRCI_INTERESES,NRCI_ISR,NRCI_TASA,NRCI_SALDO_FINAL,NPORCPARTICIPA;
        EXIT WHEN RS_REPCTASIND%NOTFOUND;
          --IF NPORCPARTICIPA > 0 THEN
            NPARTICIPACION:=0;
          --END IF;


          INSERT INTO REPCTAIND VALUES (
            NSECUENCIAL,NRCI_NUM_FIDEICOMISO,VRCI_NOM_FIDEICOMISO,
            VRCI_PERIODO,--PERIODO
            VFECHAFINAL,--FECHA
            NOMN1,--NOMBRE DE NIVEL 1
            NOMN2,--NOMBRE DE NIVEL 2
            NOMN3,--NOMBRE DE NIVEL 3
            '',--NOMBRE DEL INVERSIONISTA
            NRCI_NUM_N1,NVL(NRCI_NUM_N2,0),0,
            VRCI_NOM_N1,NVL(VRCI_NOM_N2,'N2'),
            NRCI_TASA,--NUMERO DE INVERSIONISTAS
            NRCI_SALDO_ANT,--SALDO ANTERIOR
            NRCI_TASA,
            NRCI_DEPOSITOS,NRCI_RETIROS,
            NRCI_INTERESES,--INTERESES
            NRCI_ISR,--ISR
            0,--SALDO PARCIAL
            NPARTICIPACION,--PARTICIPACION
            NRCI_SALDO_FINAL,'N/A','N/A','N/A'--SALDO FINAL
          );

        EXIT WHEN RS_REPCTASIND%NOTFOUND;
        NSECUENCIAL:=NSECUENCIAL+1;
      END LOOP;
      CLOSE RS_REPCTASIND;      

    ELSIF TIPO = 5 THEN--DETALLE POR INVERSIONISTA
      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      VN1:='';
    -- OG 06092021  DELETE FROM FID_SAL_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO;
    -- OG 06092021 DELETE FROM FID_SAL_CTAS_IND_ACUM WHERE SAL_CONTRATO = FIDEICOMISO;
      --SE EXTRAE LA CLAVE ALFANUMERICA DEL INVERSIONISTA
      IF INSTR(N1,'-1')=0 THEN
        SELECT DISTINCT DAT_CLAVE INTO VN1
        FROM FID_DATOS_EST_CTAS WHERE DAT_CONTRATO=FIDEICOMISO AND DAT_ID=N1;
      END IF;
      --SE ELIMINAN LAS TABLAS TEMPORALES
      --DELETE FROM FID_SAL_CTAS_IND WHERE SAL_CONTRATO = FIDEICOMISO;
      SELECT SUBSTR(N1, 1,
      (SELECT EST_LONG_ID FROM FID_ESTRUC_CTAS_IND WHERE EST_CONTRATO =
      FIDEICOMISO AND EST_NIVEL = 1)) INTO PN_NIVEL FROM DUAL;

      VSQL := 'SELECT  ';
      VSQL := VSQL ||  'MOV_CONTRATO AS MOV_CONTRATO,  ';
      VSQL := VSQL ||  'MOV_CLAVE_INV AS N1,  ';
      VSQL := VSQL ||  'DAT_DATO AS NomN1,  ';   
      VSQL := VSQL ||  'SUM(0) AS SALDO_INI,  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''D'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(NVL(DECODE(MOV_TIPO_OPER, ''R'',MOV_IMPORTE,0),0)),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0),  ';
      VSQL := VSQL ||  'SUM(0) as cuenta,  ';
      VSQL := VSQL ||  'SUM(0) AS SAL_PARCIAL,  ';
      VSQL := VSQL ||  '0 PARTICIPACION  ';
      VSQL := VSQL ||  'FROM  FID_MOV_CTAS_IND, ';
      VSQL := VSQL ||  'FID_DATOS_EST_CTAS,  ';
      VSQL := VSQL ||  'FID_ESTRUC_CTAS_IND  ';
      VSQL := VSQL ||  'WHERE ';
      VSQL := VSQL ||  'DAT_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  'DAT_CLAVE=MOV_CLAVE_INV AND  ';
      VSQL := VSQL ||  'EST_CONTRATO=MOV_CONTRATO AND  ';
      VSQL := VSQL ||  ' MOV_CONTRATO='||TO_CHAR(FIDEICOMISO);
      VSQL := VSQL ||  ' AND SUBSTR(MOV_CLAVE_INV,1,2)= '|| SUBSTR(N1,1,2);
      VSQL := VSQL ||  ' GROUP BY  ';
      VSQL := VSQL ||  'MOV_CONTRATO,MOV_CLAVE_INV,EST_LONG_ID,DAT_DATO  ';
      VSQL := VSQL ||  'ORDER BY   ';
      VSQL := VSQL ||  'MOV_CONTRATO,N1  ';
      OPEN RS_REPCTASIND FOR VSQL;
      LOOP
        FETCH RS_REPCTASIND INTO NRCI_NUM_FIDEICOMISO,NRCI_NUM_N1,VRCI_NOM_N1,
                                 NRCI_SALDO_ANT, NRCI_DEPOSITOS,NRCI_RETIROS,
                                 NRCI_INTERESES,NRCI_ISR,NRCI_TASA,NRCI_SALDO_FINAL,NPORCPARTICIPA;
        EXIT WHEN RS_REPCTASIND%NOTFOUND;
          --IF NPORCPARTICIPA > 0 THEN
            NPARTICIPACION:=0;
          --END IF;


          INSERT INTO REPCTAIND VALUES (
            NSECUENCIAL,NRCI_NUM_FIDEICOMISO,VRCI_NOM_FIDEICOMISO,
            VRCI_PERIODO,--PERIODO
            VFECHAFINAL,--FECHA
            NOMN1,--NOMBRE DE NIVEL 1
            NOMN2,--NOMBRE DE NIVEL 2
            NOMN3,--NOMBRE DE NIVEL 3
            '',--NOMBRE DEL INVERSIONISTA
            NRCI_NUM_N1,NVL(NRCI_NUM_N2,0),0,
            VRCI_NOM_N1,NVL(VRCI_NOM_N2,'N2'),
            NRCI_TASA,--NUMERO DE INVERSIONISTAS
            NRCI_SALDO_ANT,--SALDO ANTERIOR
            NRCI_TASA,
            NRCI_DEPOSITOS,NRCI_RETIROS,
            NRCI_INTERESES,--INTERESES
            NRCI_ISR,--ISR
            0,--SALDO PARCIAL
            NPARTICIPACION,--PARTICIPACION
            NRCI_SALDO_FINAL,'N/A','N/A','N/A'--SALDO FINAL
          );

        EXIT WHEN RS_REPCTASIND%NOTFOUND;
        NSECUENCIAL:=NSECUENCIAL+1;
      END LOOP;
      CLOSE RS_REPCTASIND;      



    END IF;
    COMMIT;
    RETURN 0;
    EXCEPTION
      WHEN OTHERS THEN
        AUX_ORA_ERR := 'OTHERS; ' || SQLERRM;
        IF LENGTH(AUX_MSG_ERR) = 0 THEN
          AUX_MSG_ERR := 'ERROR OCURRIDO EN REPORTES CTAS IND0..'||$$PLSQL_LINE||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE ;
        END IF;
        HONORARIOS.P_Err_Error_Rutina(0,
                           -1,
                           'PROCESO',
                           'REPCTAIND',
                           AUX_ORA_ERR,
                           AUX_MSG_ERR);
        RETURN -1;
    END;
  END REPORTES;
